### ISSUE TITLE
problem about tate-book-template.tex

### ISSUE THREAD

**Issue by Steve-Cheung-emct** [fnshr/latex-templates#1]
Please take a look at this, thank you very much!

! Undefined control sequence.
l.131   \bou  and \kasen 

! Undefined control sequence.
l.153 ???????€????\,\rensuji

and line 158 \sidenote

! You can't use `\prevdepth' in horizontal mode.
\nointerlineskip ->\prevdepth
                              -\@m \p@
l.170 \kundoku
              {???}{}{???}{???}

[tate-book-template.zip](https://github.com/fnshr/latex-templates/files/3055034/tate-book-template.zip)

**Comment by fnshr** [comment]
Sorry for my late reply. It seems that you haven't installed required packages (e.g. _plext_ package for \bou and \kasen). Could you tell me about your environment, such as the version of (up)LaTeX and so on?

**Comment by Steve-Cheung-emct** [comment]
Thank you for your reply.

I have tried to add ``\usepackage{plext} '' , this problem still exists.

``\sidenote'' and ``\kundoku'' still gave out a error.

**Comment by fnshr** [comment]
As I noted earlier, could you please tell me more details? Otherwise, I cannot guess what is going on...
